### ISSUE TITLE
Data Limitation

### ISSUE THREAD

**Issue by deepakchopade** [hroudaadam/mindsphere-sdk-dotnet#4]
Hi Adam,

when data is fetched for selected date range. It is returning only 2000 records. Is this limitation of timeseries API.

Thanks

**Comment by adamposledni** [comment]
Hi Deepak,

yes this is the default limitation but you can increase this limit using the request object.

```csharp
var request = new GetTimeSeriesRequest()
{
    EntityId = <asset_id>,
    PropertySetName = <aspect_id>,
    From = <from_date>,
    To = <to_date>,
    Limit = <limit_defaults_to_2000>,
    ... and more
};
var timeSeries = await iotClient.GetTimeSeriesAsync<TestTimeSeriesData>(request);
```

All this SDK does is that it wraps the MindSphere API. You can visit it's documentation here: [https://developer.mindsphere.io/apis/iot-iottimeseries/api-iottimeseries-api-swagger-3-5-0.html](https://developer.mindsphere.io/apis/iot-iottimeseries/api-iottimeseries-api-swagger-3-5-0.html)

![image](https://user-images.githubusercontent.com/47779300/132539785-d6fd6645-baa7-4e8e-bc12-cf0b80c9892f.png)

**Comment by deepakchopade** [comment]
Hi Adam,

Thanks for replying.
How i can increase the limit using a request object.

Thanks,
Deepak

**Comment by adamposledni** [comment]
If you look on my previous comment there is a code sample how to do it. 

```csharp
var request = new GetTimeSeriesRequest()
{
    EntityId = <asset_id>,
    PropertySetName = <aspect_id>,
    From = <from_date>,
    To = <to_date>,
    Limit = <set_your_limit_here>,
};
var timeSeries = await iotClient.GetTimeSeriesAsync<TestTimeSeriesData>(request);
```
